<?php
/** @var \AstoundDRudenko\PriceBadge\Pricing\Render\SimplePriceBox $block */

/** @var \AstoundDRudenko\PriceBadge\Pricing\Price\Simple\PreviousPrice $priceModel */
$previousPriceModel = $block->getPriceType('previous_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
?>
<?php if ($block->hasPreviousPrice()): ?>
    <span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($previousPriceModel->getAmount(), [
            'display_label'     => __('Previous Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'previousPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php endif; ?>
