<?php
/**
 * Product info badges template
 *
 * @var $block AstoundDRudenko\Badge\Block\Product\View\Info\Badges
 */
?>

<?php if ($block->productBadgesEnabled() && $badges = $block->getProductBadges()): ?>
    <div class="product-item-badges-wrapper">
        <?php foreach ($badges as $badgeLabel): ?>
            <div class="product-item-badge"><?= $badgeLabel ?></div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
