<?php
/** @var \AstoundDRudenko\PriceBadge\Pricing\Render\ConfigurablePriceBox $block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('previous_price');

$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<span class="normal-price">
    <?php
    $arguments = [
        'display_label' => __('Previous Price'),
        'price_id' => $block->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'previousPrice',
        'include_container' => true,
        'schema' => $schema,
    ];
    /* @noEscape */ echo $block->renderAmount($priceModel->getAmount(), $arguments);
    ?>
</span>
